# Generated by Django 4.0.4 on 2022-04-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Aadhaar_Number', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Experience', models.IntegerField()),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Earning', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Passenger2',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Email_id', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Mode_of_payment', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Trip2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_time', models.TimeField()),
                ('pickup_time', models.TimeField()),
                ('waiting_time', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('total_time', models.IntegerField()),
                ('pickup_location', models.CharField(max_length=50)),
                ('drop_location', models.CharField(max_length=50)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='Vehicle2',
            fields=[
                ('vin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Color', models.CharField(max_length=50)),
                ('AC', models.CharField(max_length=50)),
                ('WiFi', models.CharField(max_length=50)),
                ('Model_year', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Vehicle_company', models.CharField(max_length=50)),
                ('Fuel', models.CharField(max_length=50)),
                ('Prime_ride', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
