# Generated by Django 4.0.4 on 2022-04-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transections2',
            fields=[
                ('transection_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coupon', models.CharField(max_length=50)),
                ('mode_of_payment', models.CharField(max_length=50)),
            ],
        ),
    ]
