# Generated by Django 4.0.4 on 2022-04-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cab', '0002_transections2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transections2',
            table='transections',
        ),
    ]
